name: Runs unit and integration tests
on: [pull_request, push]

jobs:
    build:
        name: Run unit and integration test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: install # will run `yarn install` command
            - uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: build # will run `yarn build` command
            - uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: test # will run `yarn test` command
